import { wrap, inner, brand, h1, sub, h2, p, nav, navLink, footer } from './styles';

export const metadata = {
  title: 'Ancient Tales Publisher — Shivanchal',
  description:
    'Internal automation tool that cross-posts Ancient Tales videos from YouTube to Facebook and Instagram.',
};

export default function AncientTalesHome() {
  return (
    <div style={wrap}>
      <div style={inner}>
        <div style={brand}>Shivanchal · Internal Tool</div>
        <h1 style={h1}>Ancient Tales Publisher</h1>
        <p style={sub}>
          A single-user automation that cross-posts Ancient Tales story videos
          from YouTube to Facebook and Instagram.
        </p>

        <div style={nav}>
          <a href="/ancient-tales/privacy" style={navLink}>Privacy Policy</a>
          <a href="/ancient-tales/terms" style={navLink}>Terms of Service</a>
        </div>

        <h2 style={h2}>What this is</h2>
        <p style={p}>
          Ancient Tales Publisher is a private automation workflow built and
          operated by Shivanchal for a single content channel, Ancient Tales
          (Hindi mythology and moral-story animation). It is not a public
          product and is not available for sign-up — it exists solely to
          automate one person's own content-publishing workflow.
        </p>

        <h2 style={h2}>What it does</h2>
        <p style={p}>
          After a video is uploaded and published on the Ancient Tales YouTube
          channel, the operator pastes the YouTube link and the same video
          file into a private submission form. The automation then:
        </p>
        <ul style={{ ...p, paddingLeft: 20 }}>
          <li>Reads the video's real title, description and tags directly from the YouTube Data API (no content is rewritten or generated by AI)</li>
          <li>Stores a temporary working copy of the video file in a Google Drive folder owned by the operator</li>
          <li>Publishes the same video, with the same title and description, to the Ancient Tales Facebook Page and Instagram account</li>
          <li>Logs the publish record (title, link, date) to a private Google Sheet owned by the operator</li>
          <li>Deletes the temporary Drive copy once publishing succeeds</li>
        </ul>

        <h2 style={h2}>Who operates it</h2>
        <p style={p}>
          This tool is operated exclusively by Shivanchal for its own Ancient
          Tales channel. It connects only to Google, Facebook and Instagram
          accounts that the operator personally owns and controls.
        </p>

        <div style={footer}>
          <p>Shivanchal · Bhopal, Madhya Pradesh, India</p>
          <p>Contact: ankitdubey.aitech@gmail.com</p>
        </div>
      </div>
    </div>
  );
}
